### ISSUE TITLE
Design a logo for the app

### ISSUE THREAD

**Issue by guitarhub786** [chingu-voyages/v22-chimeras-team-04#32]

**Comment by guitarhub786** [comment]
Logo and icons for the Gmail Cleaner app.
![gmailcleaner](https://user-images.githubusercontent.com/47324512/91192931-6fc4e100-e6ee-11ea-8146-15488ecbf877.png)
![icon](https://user-images.githubusercontent.com/47324512/91192980-83704780-e6ee-11ea-8b78-a916ea4fd6d6.png)

**Comment by maknetaRo** [comment]
Looks really great. You can use those colors in landing page.
