### ISSUE TITLE
The SCSS file structure and Webpack need to be addressed. 

### ISSUE THREAD

**Issue by guitarhub786** [chingu-voyages/v22-chimeras-team-04#36]
The SCSS file structure and Webpack need to be addressed. 
The current structure is created as if there is only one user, yet we are all sharing the same Webpack and file structure.
Team members cannot share the same variable names. This can be solved by everyone using a different name but needs consultation each time to avoid clashes which are not practical.

Different file names still do not solve the problem as we are all sharing, for example, the same CSS `body`. 
```
// _variables.scss
$user1_bg-color: blue; // user1 wants their html page background to be blue
$user2_bg-color: green; // user2 wants their html page background to be green
```

```
// _layout.scss
body {
// Which one is it going to be, blue or green? 
// background-color: $user1_bg-color: blue;
// background-color: $user2_bg-color: green;
}
```

SOLUTION:
I suggest we reconfigure Webpack and file structure, so Webpack outputs for example;

```
> dist
      | main-user1.css
      | main-user2.css
```

Then each users HTML file can Link it's own `main.css` stylesheet that can be all bundled to ([dist][css]style.css). 
```
// index.html
<link href="main-user1.css" rel="stylesheet"></head>
```

```
// topTable.html
<link href="main-user2.css" rel="stylesheet"></head>
```

Unless anybody has other ideas on how to resolve this issue, this is urgent.

**Comment by maknetaRo** [comment]
If we had a design, we wouldn't have this problem because we all should have the same background and so on. The design should be uniform. Another way much simpler is to add wrappers with classes or ids and style using classes or ids.
